spring.application.name=spring-boot-devops-starter
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME:taskdb}}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:taskuser}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:taskpass}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never
management.endpoint.health.probes.enabled=true
